version: '3'
services:

  database:
    platform: linux/x86_64
    restart: always
    build: ./database
    ports:
      - "3306:3306"
    volumes:
      - ./database/sql:/docker-entrypoint-initdb.d
      - database:/var/lib/mysql
    environment:
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
    env_file:
      - ./database/.env
    tty: true
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 20s
        retries: 10

  backend:
    depends_on:
      database:
        condition: service_healthy
    platform: linux/x86_64
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    ports:
      - "8000:8000"
    env_file:
      - backend/.env

  preditor:
    platform: linux/x86_64
    build:
      context: ./model
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    ports:
      - "8001:8001"
    
  frontend:
    build: ./frontend/app
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
    database: